# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Create_Data": "00_prepare_transaction_data.ipynb",
         "Label_Data": "01_label_data.ipynb"}

modules = ["preprocess/prepare_transaction_data.py",
           "preprocess/label_data.py"]

doc_url = "https://busracikla.github.io/sample_project/"

git_url = "https://github.com/busracikla/sample_project"

def custom_doc_links(name): return None
